## YAML Template.
twitter:
    consumer_key: "UblzqTDa7NvGjN0MZZs1wDSgY"
    consumer_secret: "E0e33TiG3TcZ6BMeWEFTleZcz1hczAxWWOLwmuhAZ3j0sIEeEV"
    oauth_token: "197863336-d7GOniO5X0X82k8jFezRGRLYLvJ5g3ePfGiWRNKO"
    oauth_token_secret: "DVz7LzygKsBm1fOcWZURaW8LO6LLa6SkSYnPEDG2jir2m"    